---
- hosts: 
  become: yes
  tasks:
  - name: update and installing tomcat
    apt:
      name: tomcat9
      state: present
      update_cache: yes   
  - name: java parameters
    copy:
      src: tomcat9
      dest:  /etc/default/tomcat9
    notify:
    - Restart Tomcat9
  - name: installing tomcat packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - tomcat9-docs 
    - tomcat9-admin
    - tomcat9-examples
    - default-jdk
    - ant 
    - git 
    notify:
    - Restart Tomcat9  
  - name: tomcat web management
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9/tomcat-users.xml
  - name: Deploy WAR File
    copy:
      src: /home/ansible/AnsibleTomcat/openmars.war
      dest: /var/lib/tomcat7/webapps/openmrs.war
    notify:
    - Restart Tomcat9 
  handlers:
  - name: Restart Tomcat9
    service:
      name: tomcat9
      enabled: yes
      state: restarted         
